### ISSUE TITLE
How to specify SSH/rsync port. 

### ISSUE THREAD

**Issue by octalmage** [octalmage/WP-Unit-Test-Runner#12]
It might be useful to allow supplying the full SSH command, and this could be used for the rsync like this: 

```
 rsync -avz -e "ssh -p $portNumber" user@remoteip:/path/to/files/ /local/path/
```

It would be awesome if the ssh command could be used for both ssh and rsync.

**Comment by octalmage** [comment]
Maybe something like this would work? 

```
$WPT_SSH_COMMAND=ssh -p 2222" user@remoteip
```

**Comment by danielbachhuber** [comment]
> Maybe something like this would work?

I'd prefer to make it a bit more explicit. See #13
